name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Unzip project
        run: unzip "Fresh Hands 1.21.4.zip" -d .
      - uses: actions/setup-java@v4
        with: {java-version: '21', distribution: 'temurin'}
      - uses: gradle/actions/setup-gradle@v3
        with: {gradle-version: 8.10}
      - run: gradle build
      - uses: actions/upload-artifact@v4
        with: {name: FreshHands-Jar, path: build/libs/*.jar}
